config/routes.rb
Rails.application.routes.draw do
  resources :user_answers
  
  resources :polls do
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
    
    get 'student', on: :collection, to: 'polls#index_student'
    get 'student', on: :member, to: 'polls#show_student'
  end
    
  root 'static_pages#home'
  post '/assessment/start', to: 'static_pages#home'
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
    belongs_to :answer
    has_one :question, :through => :answer 
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  before_action :set_user_answer, only: [:show, :edit, :update, :destroy]

  # GET /user_answers
  # GET /user_answers.json
  def index
    @user_answers = UserAnswer.all
  end

  # GET /user_answers/1
  # GET /user_answers/1.json
  def show
  end

  # GET /user_answers/new
  def new
    @user_answer = UserAnswer.new
  end

  # GET /user_answers/1/edit
  def edit
  end

  # POST /user_answers
  # POST /user_answers.json
  def create
    questions = params.keys.select{ |i| i =~ /^question_(\d+)$/ }
    questions.each do |question|
      current_answer = Answer.find(params[question])
      current_answer.increment!(:votes)
      # UserAnswer.create(user_id: 0,
      #                   answer: current_answer)
      
    end
    # TODO add a success notice
    redirect_to student_polls_path
    # @user_answer = UserAnswer.new(user_answer_params)
    # respond_to do |format|
    #   if @user_answer.save
    #     format.html { redirect_to @user_answer, notice: 'User answer was successfully created.' }
    #     format.json { render :show, status: :created, location: @user_answer }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user_answer.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /user_answers/1
  # PATCH/PUT /user_answers/1.json
  def update
    respond_to do |format|
      if @user_answer.update(user_answer_params)
        format.html { redirect_to @user_answer, notice: 'User answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_answer }
      else
        format.html { render :edit }
        format.json { render json: @user_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_answers/1
  # DELETE /user_answers/1.json
  def destroy
    @user_answer.destroy
    respond_to do |format|
      format.html { redirect_to user_answers_url, notice: 'User answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_answer
      @user_answer = UserAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_answer_params
      params.fetch(:user_answer, {})
    end
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/user_answers/_form.html.erb
<%= form_for(user_answer) do |f| %>
  <% if user_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_answer.errors.count, "error") %> prohibited this user_answer from being saved:</h2>

      <ul>
      <% user_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_answers/edit.html.erb
<h1>Editing User Answer</h1>

<%= render 'form', user_answer: @user_answer %>

<%= link_to 'Show', @user_answer %> |
<%= link_to 'Back', user_answers_path %>

app/views/user_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_answers.each do |user_answer| %>
      <tr>
        <td><%= link_to 'Show', user_answer %></td>
        <td><%= link_to 'Edit', edit_user_answer_path(user_answer) %></td>
        <td><%= link_to 'Destroy', user_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Answer', new_user_answer_path %>

app/views/user_answers/new.html.erb
<h1>New User Answer</h1>

<%= render 'form', user_answer: @user_answer %>

<%= link_to 'Back', user_answers_path %>

app/views/user_answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_answer_path(@user_answer) %> |
<%= link_to 'Back', user_answers_path %>