config/routes.rb
Rails.application.routes.draw do
  resources :user_answers
  
  resources :polls do
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
    
    get 'student', on: :collection, to: 'polls#index_student'
    get 'student', on: :member, to: 'polls#show_student'
  end
    
  root 'static_pages#home'
  post '/assessment/start', to: 'static_pages#home'
end

app/models/poll.rb
class Poll < ApplicationRecord
   has_many :questions, dependent: :destroy
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :show_student, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    # TODO only show current course
    @polls = Poll.where(course_id: 1)
  end

  # GET /polls/student
  def index_student
    # TODO only show current course
    @polls = Poll.where(course_id: 1, is_open: true)
  end
  
  # GET /polls/1
  # GET /polls/1.json
  def show
  end
  
  # get /polls/1/student
  def show_student
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    # TODO: change to Poll.new and verify poll.save
    @poll = Poll.create(name: params["quiz_title"],
                  course_id: 1,
                  is_open: true)
    questions = params.keys.select{ |i| i =~ /^q\d$/ }
    all_answers = params.keys.select{ |i| i =~ /^q\da\d$/ }
    
    answer_keys = params.keys.select{ |i| i =~ /^q\dr$/ }
    correct_answers = answer_keys.map{ |i| params[i] }
    
    questions.each { |q|
    question = @poll.questions.create(text: params[q])
    
    answers = all_answers.select{ |i| i =~ /^#{q}/ }
      answers.each{ |a|
        question.answers.create(
            text: params[a],
            weight: is_answer_correct?(correct_answers, a) ? 1 : 0,
            votes: 0)
      }
    }

    # respond_to do |format|
    #   if @poll.save
    #     format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
    #     format.json { render :show, status: :created, location: @poll }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @poll.errors, status: :unprocessable_entity }
    #   end
    # end
    redirect_to :root
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.fetch(:poll, {})
    end

    def is_answer_correct?(correct_answers, answer)
      correct_answers.any? { |s| 
        s.include? answer.match(/^q\da(\d)$/).captures[0]
      }
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for(poll) do |f| %>
  <% if poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <center>
    <h1>Polls</h1>
  </center>
  <% @polls.each do |poll| %>
    <div class="row top10">
      <!-- TODO: fix for different screen sizes-->
      <div class="col-xs-9 col-xs-offset-0
                  col-sm-8 col-sm-offset-1 
                  col-md-7 col-md-offset-2 
                  col-lg-4 col-lg-offset-4">
      <!-- TODO: click doesn't work on phones. note that teachers won't be using phones much -->
        <% button_text = "Poll " + poll.id.to_s + ": \"" + poll.name.to_s + "\"" %>
        <%= link_to button_text, poll, class: "btn btn-block button-color btn-lg padded-md" %>
        <%= link_to 'Edit', edit_poll_path(poll), class: "btn btn-info btn-lg padded-md"%>
        <%= link_to 'Destroy', poll, class: "btn btn-danger btn-lg padded-md", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/index_student.erb
<div class="container">
    <h1>hello student</h1>
    <h3>please choose a poll to take</h3>
    <br/>
    <div class="row">
        <% @polls.each do |poll| %>
            <div class="col-xs-10 col-xs-offset-1
                        col-sm-8 col-sm-offset-2 
                        col-md-5 col-md-offset-1
                        col-lg-4 col-lg-offset-1">
                <% button_text = "Take Poll " + poll.id.to_s + ": \"" + poll.name.to_s + "\"" %>
                <%= link_to button_text, student_poll_path(poll.id), 
                    class: "btn btn-block button-color btn-lg padded-md top10" %>
            </div>
        <% end %>
    </div>
</div>

app/views/polls/new.html.erb
<center><h1>New Poll</h1></center>

<!--<form method="post" action="/polls">-->
<%= form_for(@poll) do |f| %>
    <div id="Quiz" class="container">
        <label for= "QuizTitle">Quiz Title</label>
        <input type="text" class="form-control" id="QuizTitle" name="quiz_title">
        
        <div id="questions">
            <div class="row">
                <div class="col-xs-9" id="question1">
                    <label for="q1">Question 1</label>
                    <div class="row">
                        <div class="col-xs-9">
                            <input type="text" class="form-control" id="q1" name="q1">
                        </div>
                        <div class="col-xs-1" >
                            <a class="btn btn-danger" onclick="removeQuestion(this.parentElement.parentElement.parentElement)">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </div>
                    </div>

                    <div id=question1answers style="border: 4px solid white" >
                        <div class="row" style="border: 4px solid white">
                            <div class="col-xs-1" id="q1radio" align="right">
                                <input type="radio" name="q1r" value="1">
                            </div>
                            
                            <div class="col-xs-6" id="q1a1">
                                <!--<label for="answer1">Answer 1</label>-->
                                <input type="text" class="form-control" id="answer1" name="q1a1">
                            </div>
                            
                            <div class="col-xs-2">
                                <!-- don't let users remove first answer -->
                                <!--
                                <a class="btn btn-danger" onclick="removeAnswer(this.parentElement.parentElement)">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </a>
                                -->
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <a class="btn button-color col-xs-offset-1" onclick="addAnswer(this.parentElement.parentElement)">
                            <span class="glyphicon glyphicon-plus"></span>
                            Add new answer
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <br></br>
        <a class="btn btn-primary" value="Add" id="poll-submit" onclick="addQuestion(this.parentElement)">
            <span class="glyphicon glyphicon-plus"></span>
            Add new question
        </a>
    </div>
    <center>
        <div style="border: 8px solid white"> 
            <input class="btn button-color btn-lg" type="submit"/>
        </div>
    </center>
<% end %>
<!--</form>-->

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<div id="Quiz" class="container">
    <!--TODO add button the show answers. hide them by default-->
    <center><h1>
        <%= link_to @poll.name, @poll %>
    </h1></center>
    <div id="questions">
        <% @poll.questions.each do |question| %>
            <table id="q<%= question.id %>" class="table">
                <tr>
                    <th colspan="4"><%= question.text %></th>
                </tr>
                <tr>
                    <th class="col-xs-1 col-sm-1">Number</th>
                    <th class="col-xs-1 col-sm-1">Correct</th>
                    <th class="col-xs-1 col-sm-1"># Votes</th>
                    <th class="col-xs-9 col-sm-9">Answer</th>
                </tr>
                <% first_answer_id = question.answers.first.id %>
                <% question.answers.each do |answer| %>
                    <tr id="<%= "q" + question.id.to_s + "a" + answer.id.to_s %>">
                        <td id="<%= "q" + question.id.to_s + "a" + answer.id.to_s + "Number"%>">
                            <%= answer.id - (first_answer_id-1) %>
                        </td>
                        <td id="<%= "q" + question.id.to_s + "a" + answer.id.to_s + "weight" %>">
                            <% if answer.correct? then %>
                                <span class='glyphicon glyphicon-ok'></span>
                            <% end %>
                        </td>
                        <td id="<%= "q" + question.id.to_s + "a" + answer.id.to_s + "votes"%>">
                            <%= answer.votes %>
                        </td>
                        <td id="<%= "q" + question.id.to_s + "a" + answer.id.to_s + "text"%>">
                            <%= answer.text %>
                        </td>
                    </tr>
                <% end %>
            </table>
            <br/>
        <% end %>
    </div>
</div>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/polls/show_student.erb
<!-- TODO make view better for phones. bigger radio button clickables-->
<div id="quiz" class="container">
    <form method='post' action='/user_answers'>
        <div id="questions">
            <% @poll.questions.each do |question| %>
                <div class="row top10">
                <%= question.text %>
                <% question.answers.each do |answer| %>
                    <div class="radio">
                        <label>
                            <input type="radio" 
                                   name="question_<%= question.id %>" 
                                   id="question<%= question.id %>answer<%= answer.id %>"
                                   value="<%= answer.id %>">
                            <%= answer.text %>
                        </label>
                    </div>
                <% end %>
                </div>
            <% end %>
        </div>
        
        <input type="submit" 
               name="commit" 
               value="Submit Poll"
               class="btn btn-lg button-color">
    </form>
</div>